version: "3.9"

services:
  devopsdb:
    image: sandeepkr98/automation:db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
    secrets:
      - root_password
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: sandeepkr98/automation:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 2
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

secrets:
  root_password:
    file: ./mysql_root_password.txt
